### ISSUE TITLE
Can I have my cookbook back?

### ISSUE THREAD

**Issue by tejaycar** [mgoldsborough/chef-ssh#1]
@mgoldsborough Any chance I can get ownership back on this cookbook in the supermarket?  Given that I've been maintaining this cookbook for the last year, and am responsible for writing a huge chunk of the current code, I think that's pretty reasonable.  Feel free to rope in @markolson who was the original author.

Thanks,
Tejay

**Comment by mgoldsborough** [comment]
Sure, but you've got to be more **way more** careful when you're managing cookbooks like this.  Our build was broke for over 24 hours while it was down.  It looked like you had unpublished it for good as there was no mention otherwise (hence me jumping on it to fix things on my end).

**Comment by tejaycar** [comment]
Yea, I get that.  It was a pretty odd situation, to say the least.  As a
side note, this is exactly why I wouldn't recommend trusting the
supermarket as your primary source.  We copy everything we use to our own
internal berks repo. That way we can vet new releases and gain protection
for dumb mistakes such as my own.

I believe I'm 'tejaycar' on supermarket.  You should be able to hand off
control that way, I believe.

**Comment by mgoldsborough** [comment]
All done.

**Comment by tejaycar** [comment]
Thanks.
